// <auto-generated />
using System;
using Kairion.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kairion.Infrastructure.Migrations
{
    [DbContext(typeof(KairionDbContext))]
    partial class KairionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kairion.Domain.ClusterAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("DeepAnalysisId")
                        .HasColumnType("uuid")
                        .HasColumnName("deep_analysis_id");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("origin");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_item_id");

                    b.Property<Guid?>("SupersedesId")
                        .HasColumnType("uuid")
                        .HasColumnName("supersedes_id");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("ix_cluster_assignments_cluster");

                    b.HasIndex("SourceItemId")
                        .HasDatabaseName("ix_cluster_assignments_source");

                    b.ToTable("cluster_assignments", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.DeepAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("context");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("CurrentSolution")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("current_solution");

                    b.Property<string>("DesiredOutcome")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("desired_outcome");

                    b.Property<string>("Dissatisfaction")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("dissatisfaction");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<decimal>("PainStrength")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("pain_strength");

                    b.Property<string>("PriceSensitivity")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("price_sensitivity");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("problem");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_id");

                    b.Property<string>("SchemaVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema_version");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_item_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<string>("Workaround")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("workaround");

                    b.HasKey("Id");

                    b.HasIndex("SourceItemId")
                        .HasDatabaseName("ix_deep_analyses_source_item");

                    b.HasIndex("SourceItemId", "SchemaVersion")
                        .HasDatabaseName("ix_deep_analyses_source_version");

                    b.ToTable("deep_analyses", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.HumanRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("action");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<Guid?>("SourceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_item_id");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("ix_human_revisions_cluster");

                    b.ToTable("human_revisions", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.Observation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClusterId")
                        .HasColumnType("uuid")
                        .HasColumnName("cluster_id");

                    b.Property<DateTime>("FirstObservedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_observed_utc");

                    b.Property<DateTime>("ObservedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_item_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceItemId")
                        .HasDatabaseName("ix_observations_source");

                    b.HasIndex("ProjectId", "ObservedUtc")
                        .HasDatabaseName("ix_observations_project_observed");

                    b.HasIndex("ProjectId", "ClusterId", "ObservedUtc")
                        .HasDatabaseName("ix_observations_project_cluster_observed");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.PainCluster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("ReviewStateVersion")
                        .HasColumnType("integer")
                        .HasColumnName("review_state_version");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_pain_clusters_project");

                    b.ToTable("pain_clusters", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.ResearchProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ArchivedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_utc");

                    b.Property<string>("BriefKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("brief_kind");

                    b.Property<string>("BriefText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("brief_text");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("EnabledSourceProviderIds")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("enabled_source_provider_ids");

                    b.Property<string>("IncludedCompetitors")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("included_competitors");

                    b.Property<string>("QueryStrategy")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("source_query_strategy");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("topics");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_utc");

                    b.Property<DateTime?>("WindowEndUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_window_end_utc");

                    b.Property<DateTime?>("WindowStartUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_window_start_utc");

                    b.HasKey("Id");

                    b.ToTable("research_projects", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.ScreeningResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("analysis_version");

                    b.Property<decimal>("CommercialHint")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("commercial_hint");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("decision");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<decimal>("Pain")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("pain");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_id");

                    b.Property<decimal>("Relevance")
                        .HasColumnType("numeric(6,4)")
                        .HasColumnName("relevance");

                    b.Property<Guid>("SourceItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_item_id");

                    b.Property<bool>("Spam")
                        .HasColumnType("boolean")
                        .HasColumnName("spam");

                    b.HasKey("Id");

                    b.HasIndex("SourceItemId")
                        .HasDatabaseName("ix_screening_results_source_item");

                    b.HasIndex("SourceItemId", "AnalysisVersion")
                        .HasDatabaseName("ix_screening_results_source_version");

                    b.ToTable("screening_results", (string)null);
                });

            modelBuilder.Entity("Kairion.Domain.SourceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("canonical_url");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_utc");

                    b.Property<Guid?>("DuplicateOfId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_id");

                    b.Property<string>("Excerpt")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)")
                        .HasColumnName("excerpt");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_id");

                    b.Property<string>("LatestObservationErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("latest_observation_error_code");

                    b.Property<int?>("LatestObservationHttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("latest_observation_http_status");

                    b.Property<string>("LatestObservationMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("latest_observation_message");

                    b.Property<DateTime>("LatestObservationObservedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("latest_observation_observed_utc");

                    b.Property<string>("LatestObservationProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("latest_observation_provider_id");

                    b.Property<string>("LatestObservationStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("latest_observation_status");

                    b.Property<DateTime>("ObservedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_utc");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("ProvenanceJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provenance_json");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider_id");

                    b.Property<DateTime?>("PublishedUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_utc");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("ObservedUtc")
                        .HasDatabaseName("ix_source_items_observed_utc");

                    b.HasIndex("ProjectId", "CanonicalUrl")
                        .HasDatabaseName("ix_source_items_canonical_url");

                    b.HasIndex("ProjectId", "ProviderId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_source_items_identity");

                    b.ToTable("source_items", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
